// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rfmagalhaes.aspnetcoreweb_efcore.infra.data;

namespace rfmagalhaes.aspnetcoreweb_efcore.Migrations
{
    [DbContext(typeof(TesteContext))]
    partial class TesteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("rfmagalhaes.aspnetcoreweb_efcore.domain.CodigoPostal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CEP");

                    b.Property<string>("Logradouro");

                    b.HasKey("Id");

                    b.ToTable("CodigoPostal");
                });
#pragma warning restore 612, 618
        }
    }
}
